// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhb7U8qMj12L1etGAygtDiAOb-8nuSpoM',
    appId: '1:440636374049:web:7711b460486610b848f760',
    messagingSenderId: '440636374049',
    projectId: 'tinder-lince-zaid',
    authDomain: 'tinder-lince-zaid.firebaseapp.com',
    storageBucket: 'tinder-lince-zaid.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxm7u37rPLkkfEtN5yUeZ2DBxEOqNM7J4',
    appId: '1:440636374049:android:724bc5a7988de59748f760',
    messagingSenderId: '440636374049',
    projectId: 'tinder-lince-zaid',
    storageBucket: 'tinder-lince-zaid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpjZ9CLgxHkOW644vw59mkx-eqX4ab2rM',
    appId: '1:440636374049:ios:71ab2bebcaea29f848f760',
    messagingSenderId: '440636374049',
    projectId: 'tinder-lince-zaid',
    storageBucket: 'tinder-lince-zaid.firebasestorage.app',
    iosClientId: '440636374049-858rsibt0nr7jhqtkh05977hirid9irk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinderLince',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpjZ9CLgxHkOW644vw59mkx-eqX4ab2rM',
    appId: '1:440636374049:ios:71ab2bebcaea29f848f760',
    messagingSenderId: '440636374049',
    projectId: 'tinder-lince-zaid',
    storageBucket: 'tinder-lince-zaid.firebasestorage.app',
    iosClientId: '440636374049-858rsibt0nr7jhqtkh05977hirid9irk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinderLince',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhb7U8qMj12L1etGAygtDiAOb-8nuSpoM',
    appId: '1:440636374049:web:1058e2d188a34ea348f760',
    messagingSenderId: '440636374049',
    projectId: 'tinder-lince-zaid',
    authDomain: 'tinder-lince-zaid.firebaseapp.com',
    storageBucket: 'tinder-lince-zaid.firebasestorage.app',
  );
}
